// Schema-driven UI definition for Cleanux — 22 pages
// Loaded via SchemaRouterService.setSchema() in app.ts

export const cleanuxSchema = {
  id: 'cleanux-schema',
  name: 'Cleanux',
  version: '1.0.0',
  app: {
    title: 'Cleanux',
    theme: { mode: 'system' as const },
    layout: 'main-layout',
  },
  pages: [
    {
      id: 'dashboard',
      name: 'Home',
      route: '/dashboard',
      layouts: [
        {
          id: 'dashboard-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: [
            'dashboard-hero',
            'dashboard-stats',
            'dashboard-quick-actions',
            'dashboard-recent-activity',
          ],
        },
      ],
      components: [
        {
          id: 'dashboard-hero',
          name: 'HeroCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'hero-card mb-6' },
        },
        {
          id: 'dashboard-stats',
          name: 'StatsGrid',
          selector: 'app-stats-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 4, class: 'grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6' },
        },
        {
          id: 'dashboard-quick-actions',
          name: 'QuickActionsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Quick Actions', class: 'glass-card matte-surface p-5' },
        },
        {
          id: 'dashboard-system-stats',
          name: 'SystemStatsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'System Stats', class: 'glass-card matte-surface p-5' },
        },
        {
          id: 'dashboard-recent-activity',
          name: 'RecentActivityCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Recent Activity', class: 'glass-card matte-surface p-5' },
        },
      ],
      canvasElements: [
        {
          id: 'dashboard-hero',
          componentId: 'app-card',
          name: 'HeroCard',
          icon: 'card',
          props: { class: 'hero-card mb-6' },
          classes: 'hero-card mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'dashboard-stats',
          componentId: 'app-stats-card',
          name: 'StatsGrid',
          icon: 'stats',
          props: { columns: 4, class: 'grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6' },
          classes: 'grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'dashboard-quick-actions',
          componentId: 'app-card',
          name: 'QuickActionsCard',
          icon: 'card',
          props: { title: 'Quick Actions', class: 'glass-card matte-surface p-5' },
          classes: 'glass-card matte-surface p-5',
          children: [],
          zIndex: 1,
        },
        {
          id: 'dashboard-system-stats',
          componentId: 'app-card',
          name: 'SystemStatsCard',
          icon: 'card',
          props: { title: 'System Stats', class: 'glass-card matte-surface p-5' },
          classes: 'glass-card matte-surface p-5',
          children: [],
          zIndex: 1,
        },
        {
          id: 'dashboard-recent-activity',
          componentId: 'app-card',
          name: 'RecentActivityCard',
          icon: 'card',
          props: { title: 'Recent Activity', class: 'glass-card matte-surface p-5' },
          classes: 'glass-card matte-surface p-5',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'files',
      name: 'Files',
      route: '/files',
      layouts: [
        {
          id: 'files-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['files-grid', 'files-quick-stats'],
        },
      ],
      components: [
        {
          id: 'files-grid',
          name: 'FileToolsGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4' },
        },
        {
          id: 'files-quick-stats',
          name: 'QuickStatsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Quick Stats', class: 'glass-card matte-surface p-6 mt-6' },
        },
      ],
      canvasElements: [
        {
          id: 'files-grid',
          componentId: 'app-card',
          name: 'FileToolsGrid',
          icon: 'grid',
          props: { columns: 3, class: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4' },
          classes: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4',
          children: [],
          zIndex: 1,
        },
        {
          id: 'files-quick-stats',
          componentId: 'app-card',
          name: 'QuickStatsCard',
          icon: 'card',
          props: { title: 'Quick Stats', class: 'glass-card matte-surface p-6 mt-6' },
          classes: 'glass-card matte-surface p-6 mt-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'clean',
      name: 'Clean',
      route: '/clean',
      layouts: [
        {
          id: 'clean-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['clean-hero', 'clean-categories', 'clean-actions', 'clean-more-options'],
        },
      ],
      components: [
        {
          id: 'clean-hero',
          name: 'CleanSummaryCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
        },
        {
          id: 'clean-categories',
          name: 'CategoryGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 2, class: 'grid grid-cols-1 sm:grid-cols-2 gap-4' },
        },
        {
          id: 'clean-actions',
          name: 'CleanActionsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface p-4 mt-6 flex items-center justify-between' },
        },
        {
          id: 'clean-more-options',
          name: 'MoreOptionsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'More Cleaning Options', class: 'mt-6' },
        },
      ],
      canvasElements: [
        {
          id: 'clean-hero',
          componentId: 'app-card',
          name: 'CleanSummaryCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'clean-categories',
          componentId: 'app-card',
          name: 'CategoryGrid',
          icon: 'grid',
          props: { columns: 2, class: 'grid grid-cols-1 sm:grid-cols-2 gap-4' },
          classes: 'grid grid-cols-1 sm:grid-cols-2 gap-4',
          children: [],
          zIndex: 1,
        },
        {
          id: 'clean-actions',
          componentId: 'app-card',
          name: 'CleanActionsCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface p-4 mt-6 flex items-center justify-between' },
          classes: 'glass-card matte-surface p-4 mt-6 flex items-center justify-between',
          children: [],
          zIndex: 1,
        },
        {
          id: 'clean-more-options',
          componentId: 'app-card',
          name: 'MoreOptionsCard',
          icon: 'card',
          props: { title: 'More Cleaning Options', class: 'mt-6' },
          classes: 'mt-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'power',
      name: 'Power',
      route: '/power',
      layouts: [
        {
          id: 'power-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['power-tools', 'power-profiles', 'power-stats-grid'],
        },
      ],
      components: [
        {
          id: 'power-tools',
          name: 'PowerToolsGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 2, class: 'grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6' },
        },
        {
          id: 'power-profiles',
          name: 'PowerProfilesCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Power Profiles', class: 'glass-card matte-surface p-6 mb-6' },
        },
        {
          id: 'power-stats-grid',
          name: 'PowerStatsGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6' },
        },
      ],
      canvasElements: [
        {
          id: 'power-tools',
          componentId: 'app-card',
          name: 'PowerToolsGrid',
          icon: 'grid',
          props: { columns: 2, class: 'grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6' },
          classes: 'grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'power-profiles',
          componentId: 'app-card',
          name: 'PowerProfilesCard',
          icon: 'card',
          props: { title: 'Power Profiles', class: 'glass-card matte-surface p-6 mb-6' },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'power-stats-grid',
          componentId: 'app-card',
          name: 'PowerStatsGrid',
          icon: 'grid',
          props: { columns: 3, class: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6' },
          classes: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'settings',
      name: 'Settings',
      route: '/settings',
      layouts: [
        {
          id: 'settings-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['settings-about', 'settings-theme', 'settings-schedule', 'settings-logging'],
        },
      ],
      components: [
        {
          id: 'settings-about',
          name: 'AboutCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'About', class: 'glass-card matte-surface' },
        },
        {
          id: 'settings-theme',
          name: 'ThemeCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Theme', class: 'glass-card matte-surface border-trace' },
        },
        {
          id: 'settings-schedule',
          name: 'ScheduleCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Maintenance Schedule', class: 'glass-card matte-surface border-trace' },
        },
        {
          id: 'settings-logging',
          name: 'LoggingCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Logging Configuration', class: 'glass-card matte-surface border-trace' },
        },
      ],
      canvasElements: [
        {
          id: 'settings-about',
          componentId: 'app-card',
          name: 'AboutCard',
          icon: 'card',
          props: { title: 'About', class: 'glass-card matte-surface' },
          classes: 'glass-card matte-surface',
          children: [],
          zIndex: 1,
        },
        {
          id: 'settings-theme',
          componentId: 'app-card',
          name: 'ThemeCard',
          icon: 'card',
          props: { title: 'Theme', class: 'glass-card matte-surface border-trace' },
          classes: 'glass-card matte-surface border-trace',
          children: [],
          zIndex: 1,
        },
        {
          id: 'settings-schedule',
          componentId: 'app-card',
          name: 'ScheduleCard',
          icon: 'card',
          props: { title: 'Maintenance Schedule', class: 'glass-card matte-surface border-trace' },
          classes: 'glass-card matte-surface border-trace',
          children: [],
          zIndex: 1,
        },
        {
          id: 'settings-logging',
          componentId: 'app-card',
          name: 'LoggingCard',
          icon: 'card',
          props: { title: 'Logging Configuration', class: 'glass-card matte-surface border-trace' },
          classes: 'glass-card matte-surface border-trace',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'cleaner',
      name: 'Quick Clean',
      route: '/cleaner',
      layouts: [
        {
          id: 'cleaner-root',
          type: 'grid',
          gap: 6,
          class: 'grid grid-cols-1 lg:grid-cols-12 gap-6',
          children: ['cleaner-tabs', 'cleaner-content'],
        },
      ],
      components: [
        {
          id: 'cleaner-tabs',
          name: 'CleanerTabs',
          selector: 'app-tabs',
          packageType: 'ui',
          category: 'tabs',
          props: { tabs: ['cache', 'trash', 'logs', 'packages'], class: 'lg:col-span-5 space-y-4' },
        },
        {
          id: 'cleaner-content',
          name: 'CleanerContent',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'lg:col-span-7 glass-card matte-surface rounded-2xl overflow-hidden' },
        },
      ],
      canvasElements: [
        {
          id: 'cleaner-tabs',
          componentId: 'app-tabs',
          name: 'CleanerTabs',
          icon: 'tabs',
          props: { tabs: ['cache', 'trash', 'logs', 'packages'], class: 'lg:col-span-5 space-y-4' },
          classes: 'lg:col-span-5 space-y-4',
          children: [],
          zIndex: 1,
        },
        {
          id: 'cleaner-content',
          componentId: 'app-card',
          name: 'CleanerContent',
          icon: 'card',
          props: { class: 'lg:col-span-7 glass-card matte-surface rounded-2xl overflow-hidden' },
          classes: 'lg:col-span-7 glass-card matte-surface rounded-2xl overflow-hidden',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'large-files',
      name: 'Large Files',
      route: '/large-files',
      layouts: [
        {
          id: 'large-files-root',
          type: 'flex',
          direction: 'column',
          gap: 4,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['large-files-stats', 'large-files-list'],
        },
      ],
      components: [
        {
          id: 'large-files-stats',
          name: 'StatsGrid',
          selector: 'app-stats-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 2, class: 'grid grid-cols-1 md:grid-cols-2 gap-4 mb-6' },
        },
        {
          id: 'large-files-list',
          name: 'FilesListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface border-trace' },
        },
      ],
      canvasElements: [
        {
          id: 'large-files-stats',
          componentId: 'app-stats-card',
          name: 'StatsGrid',
          icon: 'stats',
          props: { columns: 2, class: 'grid grid-cols-1 md:grid-cols-2 gap-4 mb-6' },
          classes: 'grid grid-cols-1 md:grid-cols-2 gap-4 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'large-files-list',
          componentId: 'app-card',
          name: 'FilesListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface border-trace' },
          classes: 'glass-card matte-surface border-trace',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'duplicate-finder',
      name: 'Duplicates',
      route: '/duplicate-finder',
      layouts: [
        {
          id: 'duplicate-finder-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['duplicate-finder-input', 'duplicate-finder-results'],
        },
      ],
      components: [
        {
          id: 'duplicate-finder-input',
          name: 'ScanInputCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card mb-6' },
        },
        {
          id: 'duplicate-finder-stats',
          name: 'StatsGrid',
          selector: 'app-stats-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6' },
        },
        {
          id: 'duplicate-finder-results',
          name: 'DuplicatesListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card' },
        },
      ],
      canvasElements: [
        {
          id: 'duplicate-finder-input',
          componentId: 'app-card',
          name: 'ScanInputCard',
          icon: 'card',
          props: { class: 'glass-card mb-6' },
          classes: 'glass-card mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'duplicate-finder-stats',
          componentId: 'app-stats-card',
          name: 'StatsGrid',
          icon: 'stats',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6' },
          classes: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'duplicate-finder-results',
          componentId: 'app-card',
          name: 'DuplicatesListCard',
          icon: 'card',
          props: { class: 'glass-card' },
          classes: 'glass-card',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'disk-usage',
      name: 'Disk Usage',
      route: '/disk-usage',
      layouts: [
        {
          id: 'disk-usage-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['disk-usage-scan', 'disk-usage-tree'],
        },
      ],
      components: [
        {
          id: 'disk-usage-scan',
          name: 'ScanInputCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface mb-6' },
        },
        {
          id: 'disk-usage-tree',
          name: 'DirectoryTreeCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface' },
        },
      ],
      canvasElements: [
        {
          id: 'disk-usage-scan',
          componentId: 'app-card',
          name: 'ScanInputCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface mb-6' },
          classes: 'glass-card matte-surface mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'disk-usage-tree',
          componentId: 'app-card',
          name: 'DirectoryTreeCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface' },
          classes: 'glass-card matte-surface',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'downloads',
      name: 'Downloads',
      route: '/downloads',
      layouts: [
        {
          id: 'downloads-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['downloads-summary', 'downloads-list'],
        },
      ],
      components: [
        {
          id: 'downloads-summary',
          name: 'DownloadsSummaryCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
        },
        {
          id: 'downloads-list',
          name: 'DownloadsListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface overflow-hidden' },
        },
      ],
      canvasElements: [
        {
          id: 'downloads-summary',
          componentId: 'app-card',
          name: 'DownloadsSummaryCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'downloads-list',
          componentId: 'app-card',
          name: 'DownloadsListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface overflow-hidden' },
          classes: 'glass-card matte-surface overflow-hidden',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'recent',
      name: 'Recent Files',
      route: '/recent',
      layouts: [
        {
          id: 'recent-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['recent-summary', 'recent-list', 'recent-apps'],
        },
      ],
      components: [
        {
          id: 'recent-summary',
          name: 'RecentSummaryCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
        },
        {
          id: 'recent-list',
          name: 'RecentListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface overflow-hidden' },
        },
        {
          id: 'recent-apps',
          name: 'AppsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Apps with Recent History', class: 'glass-card matte-surface p-5 mt-6' },
        },
      ],
      canvasElements: [
        {
          id: 'recent-summary',
          componentId: 'app-card',
          name: 'RecentSummaryCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'recent-list',
          componentId: 'app-card',
          name: 'RecentListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface overflow-hidden' },
          classes: 'glass-card matte-surface overflow-hidden',
          children: [],
          zIndex: 1,
        },
        {
          id: 'recent-apps',
          componentId: 'app-card',
          name: 'AppsCard',
          icon: 'card',
          props: { title: 'Apps with Recent History', class: 'glass-card matte-surface p-5 mt-6' },
          classes: 'glass-card matte-surface p-5 mt-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'clipboard',
      name: 'Clipboard',
      route: '/clipboard',
      layouts: [
        {
          id: 'clipboard-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['clipboard-summary', 'clipboard-list', 'clipboard-settings'],
        },
      ],
      components: [
        {
          id: 'clipboard-summary',
          name: 'ClipboardSummaryCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
        },
        {
          id: 'clipboard-list',
          name: 'ClipboardListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface overflow-hidden' },
        },
        {
          id: 'clipboard-settings',
          name: 'ClipboardSettingsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Clipboard Settings', class: 'glass-card matte-surface p-5 mt-6' },
        },
      ],
      canvasElements: [
        {
          id: 'clipboard-summary',
          componentId: 'app-card',
          name: 'ClipboardSummaryCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'clipboard-list',
          componentId: 'app-card',
          name: 'ClipboardListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface overflow-hidden' },
          classes: 'glass-card matte-surface overflow-hidden',
          children: [],
          zIndex: 1,
        },
        {
          id: 'clipboard-settings',
          componentId: 'app-card',
          name: 'ClipboardSettingsCard',
          icon: 'card',
          props: { title: 'Clipboard Settings', class: 'glass-card matte-surface p-5 mt-6' },
          classes: 'glass-card matte-surface p-5 mt-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'system',
      name: 'System',
      route: '/system',
      layouts: [
        {
          id: 'system-root',
          type: 'flex',
          direction: 'column',
          gap: 4,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['system-stats', 'system-services'],
        },
      ],
      components: [
        {
          id: 'system-stats',
          name: 'ServicesStatsGrid',
          selector: 'app-stats-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6' },
        },
        {
          id: 'system-services',
          name: 'ServicesListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface border-trace flex flex-col min-h-[400px]' },
        },
      ],
      canvasElements: [
        {
          id: 'system-stats',
          componentId: 'app-stats-card',
          name: 'ServicesStatsGrid',
          icon: 'stats',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6' },
          classes: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'system-services',
          componentId: 'app-card',
          name: 'ServicesListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface border-trace flex flex-col min-h-[400px]' },
          classes: 'glass-card matte-surface border-trace flex flex-col min-h-[400px]',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'startup',
      name: 'Startup',
      route: '/startup',
      layouts: [
        {
          id: 'startup-root',
          type: 'flex',
          direction: 'column',
          gap: 4,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['startup-stats', 'startup-list'],
        },
      ],
      components: [
        {
          id: 'startup-stats',
          name: 'StartupStatsGrid',
          selector: 'app-stats-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6' },
        },
        {
          id: 'startup-list',
          name: 'StartupListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface' },
        },
      ],
      canvasElements: [
        {
          id: 'startup-stats',
          componentId: 'app-stats-card',
          name: 'StartupStatsGrid',
          icon: 'stats',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6' },
          classes: 'grid grid-cols-1 md:grid-cols-3 gap-4 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'startup-list',
          componentId: 'app-card',
          name: 'StartupListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface' },
          classes: 'glass-card matte-surface',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'backup',
      name: 'Backup',
      route: '/backup',
      layouts: [
        {
          id: 'backup-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['backup-header', 'backup-list'],
        },
      ],
      components: [
        {
          id: 'backup-header',
          name: 'BackupHeaderCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'flex items-center justify-between mb-6' },
        },
        {
          id: 'backup-list',
          name: 'BackupListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface' },
        },
      ],
      canvasElements: [
        {
          id: 'backup-header',
          componentId: 'app-card',
          name: 'BackupHeaderCard',
          icon: 'card',
          props: { class: 'flex items-center justify-between mb-6' },
          classes: 'flex items-center justify-between mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'backup-list',
          componentId: 'app-card',
          name: 'BackupListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface' },
          classes: 'glass-card matte-surface',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'profiles',
      name: 'Profiles',
      route: '/profiles',
      layouts: [
        {
          id: 'profiles-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['profiles-header', 'profiles-editor', 'profiles-grid'],
        },
      ],
      components: [
        {
          id: 'profiles-header',
          name: 'ProfilesHeaderCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'flex items-center justify-between mb-6' },
        },
        {
          id: 'profiles-editor',
          name: 'ProfileEditorCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-surface matte-surface p-6' },
        },
        {
          id: 'profiles-grid',
          name: 'ProfilesGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' },
        },
      ],
      canvasElements: [
        {
          id: 'profiles-header',
          componentId: 'app-card',
          name: 'ProfilesHeaderCard',
          icon: 'card',
          props: { class: 'flex items-center justify-between mb-6' },
          classes: 'flex items-center justify-between mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'profiles-editor',
          componentId: 'app-card',
          name: 'ProfileEditorCard',
          icon: 'card',
          props: { class: 'glass-surface matte-surface p-6' },
          classes: 'glass-surface matte-surface p-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'profiles-grid',
          componentId: 'app-card',
          name: 'ProfilesGrid',
          icon: 'grid',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' },
          classes: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'system-repair',
      name: 'Repair',
      route: '/system-repair',
      layouts: [
        {
          id: 'system-repair-root',
          type: 'flex',
          direction: 'column',
          gap: 4,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['system-repair-tabs'],
        },
      ],
      components: [
        {
          id: 'system-repair-tabs',
          name: 'RepairTabs',
          selector: 'app-tabs',
          packageType: 'ui',
          category: 'tabs',
          props: { tabs: ['Symlinks', 'Packages', 'Cache', 'Permissions'] },
        },
      ],
      canvasElements: [
        {
          id: 'system-repair-tabs',
          componentId: 'app-tabs',
          name: 'RepairTabs',
          icon: 'tabs',
          props: { tabs: ['Symlinks', 'Packages', 'Cache', 'Permissions'] },
          classes: '',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'memory-optimizer',
      name: 'Memory',
      route: '/memory-optimizer',
      layouts: [
        {
          id: 'memory-optimizer-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['memory-charts', 'memory-optimize', 'memory-processes'],
        },
      ],
      components: [
        {
          id: 'memory-charts',
          name: 'MemoryChartsGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 2, class: 'grid grid-cols-1 md:grid-cols-2 gap-6 mb-6' },
        },
        {
          id: 'memory-optimize',
          name: 'OptimizeButton',
          selector: 'app-button',
          packageType: 'ui',
          category: 'button',
          props: { variant: 'primary', class: 'flex justify-end mb-6' },
        },
        {
          id: 'memory-processes',
          name: 'ProcessesCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Processes by Memory', class: 'glass-card matte-surface' },
        },
      ],
      canvasElements: [
        {
          id: 'memory-charts',
          componentId: 'app-card',
          name: 'MemoryChartsGrid',
          icon: 'grid',
          props: { columns: 2, class: 'grid grid-cols-1 md:grid-cols-2 gap-6 mb-6' },
          classes: 'grid grid-cols-1 md:grid-cols-2 gap-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'memory-optimize',
          componentId: 'app-button',
          name: 'OptimizeButton',
          icon: 'button',
          props: { variant: 'primary', class: 'flex justify-end mb-6' },
          classes: 'flex justify-end mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'memory-processes',
          componentId: 'app-card',
          name: 'ProcessesCard',
          icon: 'card',
          props: { title: 'Processes by Memory', class: 'glass-card matte-surface' },
          classes: 'glass-card matte-surface',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'automation',
      name: 'Automation',
      route: '/automation',
      layouts: [
        {
          id: 'automation-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['automation-cron', 'automation-exclude', 'automation-quick-actions'],
        },
      ],
      components: [
        {
          id: 'automation-cron',
          name: 'CronConfigCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: {
            title: 'Cron Schedule Configurations',
            class: 'glass-card matte-surface p-6 mb-6',
          },
        },
        {
          id: 'automation-exclude',
          name: 'ExcludeListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: {
            title: 'Global Directory Exclude Safe list',
            class: 'glass-card matte-surface p-6 mb-6',
          },
        },
        {
          id: 'automation-quick-actions',
          name: 'QuickActionsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Quick Actions', class: 'mb-6' },
        },
      ],
      canvasElements: [
        {
          id: 'automation-cron',
          componentId: 'app-card',
          name: 'CronConfigCard',
          icon: 'card',
          props: {
            title: 'Cron Schedule Configurations',
            class: 'glass-card matte-surface p-6 mb-6',
          },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'automation-exclude',
          componentId: 'app-card',
          name: 'ExcludeListCard',
          icon: 'card',
          props: {
            title: 'Global Directory Exclude Safe list',
            class: 'glass-card matte-surface p-6 mb-6',
          },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'automation-quick-actions',
          componentId: 'app-card',
          name: 'QuickActionsCard',
          icon: 'card',
          props: { title: 'Quick Actions', class: 'mb-6' },
          classes: 'mb-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'log-manager',
      name: 'Logs',
      route: '/log-manager',
      layouts: [
        {
          id: 'log-manager-root',
          type: 'flex',
          direction: 'column',
          gap: 4,
          class: 'view-layout',
          children: ['log-manager-stats', 'log-manager-tabs', 'log-manager-largest'],
        },
      ],
      components: [
        {
          id: 'log-manager-stats',
          name: 'LogStatsGrid',
          selector: 'app-stats-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 4, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4' },
        },
        {
          id: 'log-manager-tabs',
          name: 'LogTabs',
          selector: 'app-tabs',
          packageType: 'ui',
          category: 'tabs',
          props: { tabs: ['Journal', 'Rotated Logs', 'Logrotate'] },
        },
        {
          id: 'log-manager-largest',
          name: 'LargestLogsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Largest Log Files in /var/log', class: 'matte-surface p-6' },
        },
      ],
      canvasElements: [
        {
          id: 'log-manager-stats',
          componentId: 'app-stats-card',
          name: 'LogStatsGrid',
          icon: 'stats',
          props: { columns: 4, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4' },
          classes: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4',
          children: [],
          zIndex: 1,
        },
        {
          id: 'log-manager-tabs',
          componentId: 'app-tabs',
          name: 'LogTabs',
          icon: 'tabs',
          props: { tabs: ['Journal', 'Rotated Logs', 'Logrotate'] },
          classes: '',
          children: [],
          zIndex: 1,
        },
        {
          id: 'log-manager-largest',
          componentId: 'app-card',
          name: 'LargestLogsCard',
          icon: 'card',
          props: { title: 'Largest Log Files in /var/log', class: 'matte-surface p-6' },
          classes: 'matte-surface p-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'kernel-cleaner',
      name: 'Kernel',
      route: '/kernel-cleaner',
      layouts: [
        {
          id: 'kernel-cleaner-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: [
            'kernel-danger-warning',
            'kernel-boot-space',
            'kernel-current',
            'kernel-all',
            'kernel-old',
            'kernel-initramfs',
            'kernel-grub-notice',
          ],
        },
      ],
      components: [
        {
          id: 'kernel-danger-warning',
          name: 'DangerWarningBanner',
          selector: 'app-card',
          packageType: 'feedback',
          category: 'alert',
          props: {
            variant: 'error',
            class: 'bg-error/10 border border-error/30 rounded-lg p-4 mb-6',
          },
        },
        {
          id: 'kernel-boot-space',
          name: 'BootSpaceCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Boot Partition Space', class: 'glass-card matte-surface p-6' },
        },
        {
          id: 'kernel-current',
          name: 'CurrentKernelCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Current Kernel', class: 'glass-card matte-surface p-6' },
        },
        {
          id: 'kernel-all',
          name: 'AllKernelsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'All Installed Kernels', class: 'glass-card matte-surface p-6' },
        },
        {
          id: 'kernel-old',
          name: 'OldKernelsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Removable Old Kernels', class: 'glass-card matte-surface p-6' },
        },
        {
          id: 'kernel-initramfs',
          name: 'InitramfsCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Old Initramfs Files', class: 'glass-card matte-surface p-6' },
        },
        {
          id: 'kernel-grub-notice',
          name: 'GrubNoticeCard',
          selector: 'app-card',
          packageType: 'feedback',
          category: 'alert',
          props: { variant: 'warning', class: 'glass-card p-6 border-2 border-yellow-400' },
        },
      ],
      canvasElements: [
        {
          id: 'kernel-danger-warning',
          componentId: 'app-card',
          name: 'DangerWarningBanner',
          icon: 'alert',
          props: {
            variant: 'error',
            class: 'bg-error/10 border border-error/30 rounded-lg p-4 mb-6',
          },
          classes: 'bg-error/10 border border-error/30 rounded-lg p-4 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'kernel-boot-space',
          componentId: 'app-card',
          name: 'BootSpaceCard',
          icon: 'card',
          props: { title: 'Boot Partition Space', class: 'glass-card matte-surface p-6' },
          classes: 'glass-card matte-surface p-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'kernel-current',
          componentId: 'app-card',
          name: 'CurrentKernelCard',
          icon: 'card',
          props: { title: 'Current Kernel', class: 'glass-card matte-surface p-6' },
          classes: 'glass-card matte-surface p-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'kernel-all',
          componentId: 'app-card',
          name: 'AllKernelsCard',
          icon: 'card',
          props: { title: 'All Installed Kernels', class: 'glass-card matte-surface p-6' },
          classes: 'glass-card matte-surface p-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'kernel-old',
          componentId: 'app-card',
          name: 'OldKernelsCard',
          icon: 'card',
          props: { title: 'Removable Old Kernels', class: 'glass-card matte-surface p-6' },
          classes: 'glass-card matte-surface p-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'kernel-initramfs',
          componentId: 'app-card',
          name: 'InitramfsCard',
          icon: 'card',
          props: { title: 'Old Initramfs Files', class: 'glass-card matte-surface p-6' },
          classes: 'glass-card matte-surface p-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'kernel-grub-notice',
          componentId: 'app-card',
          name: 'GrubNoticeCard',
          icon: 'alert',
          props: { variant: 'warning', class: 'glass-card p-6 border-2 border-yellow-400' },
          classes: 'glass-card p-6 border-2 border-yellow-400',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'reports',
      name: 'Reports',
      route: '/reports',
      layouts: [
        {
          id: 'reports-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['reports-generate', 'reports-chart', 'reports-history'],
        },
      ],
      components: [
        {
          id: 'reports-generate',
          name: 'GenerateButton',
          selector: 'app-button',
          packageType: 'ui',
          category: 'button',
          props: { variant: 'primary', class: 'flex items-center justify-end mb-6' },
        },
        {
          id: 'reports-chart',
          name: 'ChartCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Space Reclaimed Over Time', class: 'glass-card matte-surface mb-6' },
        },
        {
          id: 'reports-history',
          name: 'HistoryCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { title: 'Cleaning History', class: 'glass-card matte-surface' },
        },
      ],
      canvasElements: [
        {
          id: 'reports-generate',
          componentId: 'app-button',
          name: 'GenerateButton',
          icon: 'button',
          props: { variant: 'primary', class: 'flex items-center justify-end mb-6' },
          classes: 'flex items-center justify-end mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'reports-chart',
          componentId: 'app-card',
          name: 'ChartCard',
          icon: 'card',
          props: { title: 'Space Reclaimed Over Time', class: 'glass-card matte-surface mb-6' },
          classes: 'glass-card matte-surface mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'reports-history',
          componentId: 'app-card',
          name: 'HistoryCard',
          icon: 'card',
          props: { title: 'Cleaning History', class: 'glass-card matte-surface' },
          classes: 'glass-card matte-surface',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'processes',
      name: 'Processes',
      route: '/processes',
      layouts: [
        {
          id: 'processes-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['processes-header', 'processes-list'],
        },
      ],
      components: [
        {
          id: 'processes-header',
          name: 'ProcessesHeader',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'flex items-center justify-between mb-6' },
        },
        {
          id: 'processes-list',
          name: 'ProcessesListCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface' },
        },
      ],
      canvasElements: [
        {
          id: 'processes-header',
          componentId: 'app-card',
          name: 'ProcessesHeader',
          icon: 'card',
          props: { class: 'flex items-center justify-between mb-6' },
          classes: 'flex items-center justify-between mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'processes-list',
          componentId: 'app-card',
          name: 'ProcessesListCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface' },
          classes: 'glass-card matte-surface',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'media-cleaner',
      name: 'Media',
      route: '/media-cleaner',
      layouts: [
        {
          id: 'media-cleaner-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['media-tabs', 'media-refresh'],
        },
      ],
      components: [
        {
          id: 'media-tabs',
          name: 'MediaTabs',
          selector: 'app-tabs',
          packageType: 'ui',
          category: 'tabs',
          props: { tabs: ['Steam', 'Spotify', 'VLC', 'Thumbnails', 'Icons'] },
        },
        {
          id: 'media-refresh',
          name: 'RefreshButton',
          selector: 'app-button',
          packageType: 'ui',
          category: 'button',
          props: { variant: 'primary', class: 'flex justify-end mt-6' },
        },
      ],
      canvasElements: [
        {
          id: 'media-tabs',
          componentId: 'app-tabs',
          name: 'MediaTabs',
          icon: 'tabs',
          props: { tabs: ['Steam', 'Spotify', 'VLC', 'Thumbnails', 'Icons'] },
          classes: '',
          children: [],
          zIndex: 1,
        },
        {
          id: 'media-refresh',
          componentId: 'app-button',
          name: 'RefreshButton',
          icon: 'button',
          props: { variant: 'primary', class: 'flex justify-end mt-6' },
          classes: 'flex justify-end mt-6',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'container-cleaner',
      name: 'Containers',
      route: '/container-cleaner',
      layouts: [
        {
          id: 'container-cleaner-root',
          type: 'flex',
          direction: 'column',
          gap: 4,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['container-header', 'container-tabs'],
        },
      ],
      components: [
        {
          id: 'container-header',
          name: 'ContainerHeader',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'flex items-center justify-between mb-4' },
        },
        {
          id: 'container-tabs',
          name: 'ContainerTabs',
          selector: 'app-tabs',
          packageType: 'ui',
          category: 'tabs',
          props: { tabs: ['Docker', 'Podman'] },
        },
      ],
      canvasElements: [
        {
          id: 'container-header',
          componentId: 'app-card',
          name: 'ContainerHeader',
          icon: 'card',
          props: { class: 'flex items-center justify-between mb-4' },
          classes: 'flex items-center justify-between mb-4',
          children: [],
          zIndex: 1,
        },
        {
          id: 'container-tabs',
          componentId: 'app-tabs',
          name: 'ContainerTabs',
          icon: 'tabs',
          props: { tabs: ['Docker', 'Podman'] },
          classes: '',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'dev-cleaner',
      name: 'Dev Cache',
      route: '/dev-cleaner',
      layouts: [
        {
          id: 'dev-cleaner-root',
          type: 'flex',
          direction: 'column',
          gap: 4,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['dev-cleaner-header', 'dev-cleaner-grid'],
        },
      ],
      components: [
        {
          id: 'dev-cleaner-header',
          name: 'DevCleanerHeader',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'mb-4 flex items-center justify-between' },
        },
        {
          id: 'dev-cleaner-grid',
          name: 'DevToolsGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' },
        },
      ],
      canvasElements: [
        {
          id: 'dev-cleaner-header',
          componentId: 'app-card',
          name: 'DevCleanerHeader',
          icon: 'card',
          props: { class: 'mb-4 flex items-center justify-between' },
          classes: 'mb-4 flex items-center justify-between',
          children: [],
          zIndex: 1,
        },
        {
          id: 'dev-cleaner-grid',
          componentId: 'app-card',
          name: 'DevToolsGrid',
          icon: 'grid',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' },
          classes: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'package-deep-clean',
      name: 'Packages',
      route: '/package-deep-clean',
      layouts: [
        {
          id: 'package-deep-clean-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['package-header', 'package-tabs'],
        },
      ],
      components: [
        {
          id: 'package-header',
          name: 'PackageHeaderCard',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
        },
        {
          id: 'package-tabs',
          name: 'PackageTabs',
          selector: 'app-tabs',
          packageType: 'ui',
          category: 'tabs',
          props: { tabs: ['APT', 'DNF/YUM', 'Pacman', 'Zypper'] },
        },
      ],
      canvasElements: [
        {
          id: 'package-header',
          componentId: 'app-card',
          name: 'PackageHeaderCard',
          icon: 'card',
          props: { class: 'glass-card matte-surface p-6 mb-6' },
          classes: 'glass-card matte-surface p-6 mb-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'package-tabs',
          componentId: 'app-tabs',
          name: 'PackageTabs',
          icon: 'tabs',
          props: { tabs: ['APT', 'DNF/YUM', 'Pacman', 'Zypper'] },
          classes: '',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'app-residue-cleaner',
      name: 'Residue',
      route: '/app-residue-cleaner',
      layouts: [
        {
          id: 'app-residue-cleaner-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['residue-warning', 'residue-tabs', 'residue-preview'],
        },
      ],
      components: [
        {
          id: 'residue-warning',
          name: 'BackupWarningBanner',
          selector: 'app-card',
          packageType: 'feedback',
          category: 'alert',
          props: {
            variant: 'warning',
            class: 'bg-warning/10 border border-warning/30 rounded-lg p-4',
          },
        },
        {
          id: 'residue-tabs',
          name: 'ResidueTabs',
          selector: 'app-tabs',
          packageType: 'ui',
          category: 'tabs',
          props: { tabs: ['User Configs', 'User Data', 'User Caches', 'System Orphans'] },
        },
        {
          id: 'residue-preview',
          name: 'PreviewModal',
          selector: 'app-modal',
          packageType: 'feedback',
          category: 'modal',
          props: { title: 'Preview - Items to be Deleted' },
        },
      ],
      canvasElements: [
        {
          id: 'residue-warning',
          componentId: 'app-card',
          name: 'BackupWarningBanner',
          icon: 'alert',
          props: {
            variant: 'warning',
            class: 'bg-warning/10 border border-warning/30 rounded-lg p-4',
          },
          classes: 'bg-warning/10 border border-warning/30 rounded-lg p-4',
          children: [],
          zIndex: 1,
        },
        {
          id: 'residue-tabs',
          componentId: 'app-tabs',
          name: 'ResidueTabs',
          icon: 'tabs',
          props: { tabs: ['User Configs', 'User Data', 'User Caches', 'System Orphans'] },
          classes: '',
          children: [],
          zIndex: 1,
        },
        {
          id: 'residue-preview',
          componentId: 'app-modal',
          name: 'PreviewModal',
          icon: 'modal',
          props: { title: 'Preview - Items to be Deleted' },
          classes: '',
          children: [],
          zIndex: 1,
        },
      ],
    },
    {
      id: 'advanced-cleaner',
      name: 'Advanced',
      route: '/advanced-cleaner',
      layouts: [
        {
          id: 'advanced-cleaner-root',
          type: 'flex',
          direction: 'column',
          gap: 6,
          class: 'view-layout max-w-4xl mx-auto',
          children: ['advanced-grid', 'advanced-refresh'],
        },
      ],
      components: [
        {
          id: 'advanced-grid',
          name: 'JunkCategoriesGrid',
          selector: 'app-card',
          packageType: 'data',
          category: 'card',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6' },
        },
        {
          id: 'advanced-refresh',
          name: 'RefreshButton',
          selector: 'app-button',
          packageType: 'ui',
          category: 'button',
          props: { variant: 'primary', class: 'flex justify-end mt-8' },
        },
      ],
      canvasElements: [
        {
          id: 'advanced-grid',
          componentId: 'app-card',
          name: 'JunkCategoriesGrid',
          icon: 'grid',
          props: { columns: 3, class: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6' },
          classes: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
          children: [],
          zIndex: 1,
        },
        {
          id: 'advanced-refresh',
          componentId: 'app-button',
          name: 'RefreshButton',
          icon: 'button',
          props: { variant: 'primary', class: 'flex justify-end mt-8' },
          classes: 'flex justify-end mt-8',
          children: [],
          zIndex: 1,
        },
      ],
    },
  ],
  layouts: [
    {
      id: 'main-layout',
      type: 'flex',
      direction: 'column',
      gap: 0,
      class:
        'min-h-screen bg-white dark:bg-zinc-900 text-zinc-900 dark:text-white font-sans flex flex-col overflow-x-hidden antialiased',
      children: ['header', 'content', 'bottom-nav'],
    },
    { id: 'header', type: 'stack', class: 'pt-14' },
    {
      id: 'content',
      type: 'flex',
      direction: 'column',
      gap: 0,
      class: 'flex-1 flex flex-col min-h-0 relative',
      children: ['scroll-content'],
    },
    { id: 'scroll-content', type: 'stack', class: 'flex-1 min-h-0 overflow-y-auto' },
    { id: 'bottom-nav', type: 'stack' },
  ],
};
