import {
  CRITICAL_JUNK_SIZE,
  WARNING_JUNK_SIZE,
  DEFAULT_JUNK_THRESHOLD,
  HEALTHY_SCORE,
  WARNING_SCORE,
  CRITICAL_SCORE,
} from '../../models/types-generated';

export {
  CRITICAL_JUNK_SIZE,
  WARNING_JUNK_SIZE,
  DEFAULT_JUNK_THRESHOLD,
  HEALTHY_SCORE,
  WARNING_SCORE,
  CRITICAL_SCORE,
};