export const SCAN_COMPLETE_TIMEOUT_MS = 500;
export const UPDATE_CHECK_TIMEOUT_MS = 1000;
export const MEMORY_REFRESH_INTERVAL_MS = 3000;
export const TEMPERATURE_REFRESH_INTERVAL_MS = 3000;
export const THEME_TRANSITION_TIMEOUT_MS = 300;
