#[path = "automation.route.rs"]
pub mod automation_command;
#[path = "cleaner.route.rs"]
pub mod cleaner_command;
#[path = "macros.rs"]
pub mod crud_macros;
#[path = "dashboard.route.rs"]
pub mod dashboard_command;
#[path = "health.route.rs"]
pub mod health_command;
#[path = "log.route.rs"]
pub mod log_command;
#[path = "monitor.route.rs"]
pub mod monitor_command;
#[path = "package.route.rs"]
pub mod package_command;
#[path = "profile.route.rs"]
pub mod profile_command;
#[path = "report.route.rs"]
pub mod report_command;
#[path = "storage.route.rs"]
pub mod storage_command;
#[path = "system.route.rs"]
pub mod system_command;
